from __future__ import annotations

import base64
from pathlib import Path
from typing import Any

ICON_ICO_B64 = "AAABAAIAICAQAAEABADoAgAAJgAAABAQEAABAAQAKAEAAA4DAAAoAAAAIAAAAEAAAAABAAQAAAAAAIACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAICAgADAwMAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAd3d3d3d3d3d3d3d3d3d3cAAAAAAAAAAAAAAAAAAAAHCZmqqqqqqZmaqqqZmaqpBwmZqqqqqqmZmqqqmZmqqQcJmaqqqqqpmZqqqpmZqqkHCZmqqqqqqZmaqqqZmaqpBwmZqqqqqqmZmqqqmZmqqQcJmaqqqqqpmZqqqpmZqqkHCZmqqqqqqZmaqqqZmaqpBwmZqqqqqqmZmqqqmZmqqQcJd3d3d3d3d3d3qpmZqqkHAAAAAAAAAAAAB6qZmaqpBwCIiIiIiIiIiAeqmZmqqQcAgAAAiIiACIgHAAAAAAAAAIAAAAiIgAiIBwAAAAAAAACACIAAiIAIiAcAAAAAAAAAgAiIAIiACIgHAAAAAAAAAIAIgACIgAiIBwAAAAAAAACAAAAIiIAIiAcAAAAAAAAAgAAACIiACIgHAAAAAAAAAIAIgACIgAiIBwAAAAAAAACACIgAiIAIiAcAAAAAAAAAgAiAAIiACIgHAAAAAAAAAIAAAAiAAAAIBwAAAAAAAACAAACIgAAACAcAAAAAAAAAiIiIiIiIiIgHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////////////gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAA//gAAP/4AAD/+AAA//gAAP/4AAD/+AAA//gAAP/4AAD/+AAA//gAAP/4AAD/+AAB////////////8oAAAAEAAAACAAAAABAAQAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAgAAAAICAAIAAAACAAIAAgIAAAICAgADAwMAAAAD/AAD/AAAA//8A/wAAAP8A/wD//wAA////AAd3d3d3d3d3AAAAAAAAAAcKqpmamZmpBwqqmZqZmakHB3d3d3d3qQcAAAAAAAepBwiIiIiIB6kHCACIgIgHAAAICAiAiAcAAAgICICIBwAACACIgIgHAAAICAiAiAcAAAgICICIBwAACACIAAgHAAAIiIiIiAcAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAADwAAAB8AAA=="
ICON_PNG_B64 = "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAyUlEQVR4nO2XXRLCIAyENw4H42auN8vN8KGMg5Hyo1B1yr50SlP2a8g0AJxdEq9h8Hz9AKr6kbP3HiRBsgvC2UmsUrDccxvTq0stYM90lLIAqpr9cjtu74cBpAazVQSYnX7AFOGe8cxMVItwtrqK8DCAFGS2VhE6VBrRG+Y9jU2eMtBqVoyL9sG0JEmwgmxdkGR4AByx3jk5YIO+kd8DAIBrBJCGFSylt1e/+SdcAAvgVAAOMKeJhl39S0jmnVKM2GGSo05GS/+nO1TNSAmVTHStAAAAAElFTkSuQmCC"


def apply_window_icon(root: Any) -> None:
    try:
        import tkinter as tk

        image = tk.PhotoImage(data=ICON_PNG_B64)
        root.iconphoto(True, image)
        root._dmtorrent2part_icon = image
    except Exception:
        pass


def write_ico(path: str | Path) -> Path:
    target = Path(path)
    target.write_bytes(base64.b64decode(ICON_ICO_B64))
    return target
